In [3]:
# 1. Mount your Google Drive so your file is saved safely
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

# 2. Set up your Git identity
!git config --global user.email "nehemiahkalikenka@gmail.com"
!git config --global user.name "nehemiahkalikenka"

# 3. Define your repository variables
USERNAME = "nehemiahkalikenka"
TOKEN = "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" # Paste your GitHub PAT here
REPO = "CSC4792_Group_30_Lusangazi_Town_Council_Data_Mining" # The name of the repo you want to push to

# 4. Clone your empty or existing repository into Colab
!git clone https://{USERNAME}:{TOKEN}@github.com/{USERNAME}/{REPO}.git

# 5. Move into the cloned repository folder
%cd {REPO}

# 6. Copy your current notebook from Google Drive into this Git folder
# Note: Change 'Untitled.ipynb' to whatever your notebook is currently named
!cp "/content/drive/MyDrive/Colab Notebooks/Untitled.ipynb" ./

# 7. Stage, commit, and push the file to GitHub
!git add .
!git commit -m "Initial commit of Colab notebook"
!git push origin main

Mounted at /content/drive
Cloning into 'CSC4792_Group_30_Lusangazi_Town_Council_Data_Mining'...
warning: You appear to have cloned an empty repository.
/content/CSC4792_Group_30_Lusangazi_Town_Council_Data_Mining
cp: cannot stat '/content/drive/MyDrive/Colab Notebooks/Untitled.ipynb': No such file or directory
On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/nehemiahkalikenka/CSC4792_Group_30_Lusangazi_Town_Council_Data_Mining.git'

#### Group 30

Members:


*   Nehemiah Kalikenka 2022048156

# Lusangazi Town Council Multi-Source Dataset

CSC 4792: Data Mining and Warehousing

Group 30

This notebook documents the collection, extraction, cleaning,
preprocessing and preparation of data relating to Lusangazi
Town Council.

In [ ]:
!pip install PyMuPDF
import requests
import pandas as pd
from bs4 import BeautifulSoup
import fitz
import re
import os

Requirement already satisfied: PyMuPDF in /usr/local/lib/python3.13/dist-packages (1.28.2)
warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [ ]:
BASE_URL = "https://www.lusangazicouncil.gov.zm"

Test if the website is responsive

In [ ]:
response = requests.get(BASE_URL, timeout=30, verify=False)

print(response.status_code)
print(response.url)

/usr/local/lib/python3.13/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.lusangazicouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
https://www.lusangazicouncil.gov.zm/

Now to discovery the URLs on the site

In [ ]:
from urllib.parse import urljoin
html = response.text

soup = BeautifulSoup(html, "html.parser")

links = []

for a in soup.find_all("a", href=True):
    url = urljoin(BASE_URL, a["href"])
    links.append(url)

links = list(set(links))

print(f"Found {len(links)} URLs")

for url in links[:30]:
    print(url)

Found 48 URLs
https://www.lusangazicouncil.gov.zm/?page_id=3364
https://www.lusangazicouncil.gov.zm/?page_id=2884
https://www.lusangazicouncil.gov.zm#CDFSection
https://www.lusangazicouncil.gov.zm/?page_id=3345
http://www.lusangazicouncil.gov.zm/wp-content/uploads/2023/01/CDF-GUIDELINES-2.pdf
https://www.lusangazicouncil.gov.zm/?page_id=2403
https://www.lusangazicouncil.gov.zm/?p=4737
https://www.lusangazicouncil.gov.zm/?page_id=3312
https://www.lusangazicouncil.gov.zm/?page_id=275
https://www.lgsc.gov.zm/
https://www.lusangazicouncil.gov.zm/?page_id=932
https://www.lusangazicouncil.gov.zm/?page_id=118
https://www.lusangazicouncil.gov.zm/?page_id=2131
https://www.lusangazicouncil.gov.zm/
https://www.mofnp.gov.zm/
http://www.clgti.co.zm/
https://www.lusangazicouncil.gov.zm/?page_id=3353
https://www.lusangazicouncil.gov.zm/?page_id=3331
https://www.lusangazicouncil.gov.zm/?p=4729
https://www.lusangazicouncil.gov.zm/?p=4720
https://www.lusangazicouncil.gov.zm/?page_id=2186
https://www.lusangazicouncil.gov.zm/?page_id=2249
https://www.lusangazicouncil.gov.zm/?page_id=3351
https://www.lusangazicouncil.gov.zm
https://www.lgazambia.org.zm/hub/about
https://web.facebook.com/profile.php?id=100069174820955
https://www.lusangazicouncil.gov.zm/?page_id=3359
https://www.lusangazicouncil.gov.zm/?page_id=187
https://www.lusangazicouncil.gov.zm/?page_id=1032
https://www.lusangazicouncil.gov.zm/?page_id=3354

In [ ]:
def is_internal(url):
    return urlparse(url).netloc == urlparse(BASE_URL).netloc

In [ ]:
from urllib.parse import urlparse, urljoin

# Definition of is_internal using urlparse
def is_internal(url):
    return urlparse(url).netloc == urlparse(BASE_URL).netloc

# List comprehension filtering internal links
internal_links = [
    url for url in links
    if is_internal(url)
]

This function is used to download the web pages

In [ ]:
import requests
import urllib3

# Suppress the InsecureRequestWarning when verify=False is used
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def download_page(url):
    try:
        response = requests.get(
            url,
            timeout=30,
            headers={
                "User-Agent": "Mozilla/5.0"
            },
            verify=False  # Disables SSL certificate verification
        )

        if response.status_code == 200:
            return response.text

        print(f"Failed: {url} [{response.status_code}]")
        return None

    except Exception as e:
        print(f"Error: {url} -> {e}")
        return None

Test the download function

In [ ]:
page_id_932 = download_page(
    "https://www.lusangazicouncil.gov.zm/?page_id=932"
)

print(len(page_id_932))

471827

The following script is used to exract text from the pages

In [ ]:
def extract_text(html):
    soup = BeautifulSoup(html, "html.parser")

    # Remove things we don't need
    for element in soup(["script", "style", "nav", "footer"]):
        element.decompose()

    text = soup.get_text(separator=" ", strip=True)

    return text

In [ ]:
text = extract_text(page_id_932)

print(text[:3000])

CDF Tracker – Lusangazi Town Council Menu Search Msanzala Constituency Edit 2022 CDF Edit Community Projects No. Project Name Project Description Sector Type Ward Zone Project Site/Location 1 Construction of classroom block Construction of 1*2 classroom block at Malengo community School Education Construction Chingolo Malengo Malengo community School 2 Construction of classroom block Construction of 1*2 classroom block at Chingolo community Education Construction Chingolo Malengo Chingolo community 3 Grading of the feeder road Grading of the feeder road from Sikalinda Village to Kalama farms (it passes through in five zones of the ward) approximately 45km Infrastructure Grading Chingolo Nyakachonko Sikalinda Village to Kalama farms (it passes through in five zones of the ward) 4 Construction of a classroom Construction of a 1*3 classroom at Choteta community Education Construction Lusangazi Choteta Choteta community 5 Rehabilitation of classroom and completion of a classroom block at Chibale Rehabilitation of 1*2 classroom and completion of a 1*2 classroom block at Chibale Primary School Education Rehabilitation/Completion Lusangazi Chibale Chibale Primary School 6 construction of classroom block construction of 1*3 classroom block at Maila Secondary School Education Construction Chisangu Maila Maila Secondary School 7 Construction of classroom block Construction of 1*2 classroom block at Njazi community Education Construction Chisangu Njazi Community Njazi community 8 Rehabilitation of a classroom block Rehabilitation of a 1*4 classroom block at Mwanika Community School Education Rehabilitation Chisangu Mwanika Mwanika Community School 9 Construction of a classroom block a Construction of a 1*3 classroom block at Kalumbi Primary Education Construction Singozi Kalumbi Kalumbi Primary 10 Rehabilitation of a staff house at Chikuse Primary School Rehabilitation of a staff house at Chikuse Primary School Education Rehabilitation Singozi Chikuse Chikuse Primary School 11 Completion of classroom block Completion of 1×3 classroom block at Sasu Primary School Education completion Singozi Chikuse Sasu Primary School 12 Construction of class room block School Construction of 1*2 class room block School at Kamunga community Education Construction Singozi Kamunga Kamunga community 13 Construction of class room block Construction of 1*3 class room block at Chitwelele community school Education Construction Mateyo Mzeka Misolo Chitwelele community school 14 Construction of class room block Construction of 1*2 class room block at Chamaleje community School Education Construction Mateyo Mzeka Nsenya Chamaleje community School 15 Rehabilitation of a stuff house Rehabilitation of a stuff house at  Misolo health clinic Health Rehabilitation Mateyo Mzeka Misolo Misolo health clinic 16 Drilling and equipping of boreholes Drilling and equipping of boreholes at Pondani, Mankandu village Nyalongo-Chisenga, Misefi Village and Kakwiya Water and Sanitation Drilling Mateyo

Now we use the page in a dataframe

In [ ]:
df_page_id_932 = pd.read_html(page_id_932)
print(f"Found {len(df_page_id_932)} tables")

/tmp/ipykernel_1336/2683178997.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_page_id_932 = pd.read_html(page_id_932)

Found 10 tables

In [ ]:
for i, table in enumerate(df_page_id_932):
    print("\nTABLE", i)
    display(table.head())

TABLE 0

,0,1,2,3,4,5,6,7
0,No.,Project Name,Project Description,Sector,Type,Ward,Zone,Project Site/Location
1,1,Construction of classroom block,Construction of 1*2 classroom block at Malengo...,Education,Construction,Chingolo,Malengo,Malengo community School
2,2,Construction of classroom block,Construction of 1*2 classroom block at Chingol...,Education,Construction,Chingolo,Malengo,Chingolo community
3,3,Grading of the feeder road,Grading of the feeder road from Sikalinda Vill...,Infrastructure,Grading,Chingolo,Nyakachonko,Sikalinda Village to Kalama farms (it passes t...
4,4,Construction of a classroom,Construction of a 1*3 classroom at Choteta com...,Education,Construction,Lusangazi,Choteta,Choteta community

TABLE 1

,0,1,2,3,4
0,No.,Name of Group,Type of Group (Women/Youth/Community),Amount Approved by PLGO,Date of Approval
1,1,CHIPONZI M.P.C SOCIETY,Community,6000,20/10/2022
2,2,KALYANGO WOMEN DEV,women,6000,20/10/2022
3,3,KANYANGA WOMENS DEV CLUB,women,6000,20/10/2022
4,4,TOTHO YOUTH M.P.C SOCIETY LTD,Youth,6000,20/10/2022

TABLE 2

,0,1,2,3,4,5,6,7,8
0,No.,Name of Student,Ward,Sex (M/F),Name of Skill/Programme,Level of Skill e.g Certificate or Diploma,Programme Duration (months),Training Institute(District),Training Institute (TEVET/ZNS)
1,1,Lazarus Banda,Chisangu,Male,Plumbing and pipe fitting TtL1,Trade test level 1,24,Ukwimi Trades Training Institute,Lusangazi
2,2,Andrew Phiri,Mudonsa,Male,Brick Layering and Plastering TtL1,Trade test level 1,24,Ukwimi Trades Training Institute,Lusangazi
3,3,Gibson Ndhlovu,Mudonsa,Male,Plumbing & Sheet Metal Ttl1,Trade test level 1,24,Ukwimi Trades Training Institute,Lusangazi
4,4,Lameck phiri,Singozi,Male,Brick Layering & Plastering Ttl1,Trade test level 1,NaN,Ukwimi Trades Training Institute,Lusangazi

TABLE 3

,0,1,2,3,4,5,6
0,No.,Name of Pupil,Ward,Sex (M/F),Grade,Name of School,School Location(District)
1,1,IWELL TEMBO,CHINGOLO,MALE,8,NYAMPHANDE BOARDING SECONDARY SCHOOL,Lusangazi
2,2,NICODEMAS SIMPASA,CHINGOLO,MALE,10,NYAMPHANDE BOARDING SECONDARY SCHOOL,Lusangazi
3,3,SHILOH TEMBO,CHINGOLO,MALE,10,NYAMPHANDE BOARDING SECONDARY SCHOOL,Lusangazi
4,4,CHISOMO BANDA,CHISANGU,FEMALE,19,SONJA GIRLS SECONDARY SCHOOL,Lusangazi

TABLE 4

,0,1,2,3,4
0,2023 CDF APPROVED COMMUNITY PROJECTS,2023 CDF APPROVED COMMUNITY PROJECTS,2023 CDF APPROVED COMMUNITY PROJECTS,2023 CDF APPROVED COMMUNITY PROJECTS,2023 CDF APPROVED COMMUNITY PROJECTS
1,S/N,NAME OF THE PROJECT,WARD,TECHNICAL APPRAISAL COMMENTS,RECOMMENDATION
2,1.,Construction of a 1X3 classroom block at Nyalu...,MAWANDA,There is need of a CRB as the School has no pr...,APPROVAL
3,2.,Construction of a 1X3 classroom block at Mango...,CHISANGU,There is need of a CRB as the School has no pr...,APPROVAL
4,3.,Construction of a health post at Sopa Zone,MUDONSA,Community needs a healthy post as part of the ...,APPROVAL

TABLE 5

,0,1,2,3,4
0,12.0,Completion of a stuff house at Matonga Clinic,NaN,The is no stuff house at the health post and l...,APPROVAL
1,13.0,Construction of a 1X3 classroom block at Masom...,CHINGOLO,There is need of a CRB as the School has no pr...,APPROVAL
2,14.0,Construction of a health post at Ndambwe Zone,SINGOZI,Community needs a healthy post as part of the ...,APPROVAL
3,15.0,Procurement of 2000 desks,ALL WARDS,Almost all Schools require desk and this is al...,APPROVAL

TABLE 6

     0        1        2                                                  3
0  S/N     WARD     ZONE                                    NAME OF PROJECT
1    1  Mawanda  Mawanda  Electrical Installation in the Computer labora...
2    1  Mawanda  Mawanda  Construction of Spoon drains around Computer l...
3    1  Mawanda  Mawanda  Procurement of 10 Desktops for the Computer La...
4    1  Mawanda   Matipi  Completion of 1X2 Classroom Block at Kachewere...

TABLE 7

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,No.,Name of Group,Type of Group (Women/Youth/Community),Males,Females,Youths,Total Number of males & females,Differently abled male,Differently abled Female,Registration Body,Ward,Type of Venture(specify),Amount Approved by PLGO
1,1,LUBVUUNGA SAVING AND CREDIT COOPERATIVE,Community,8,2,0,10,4,1,coperative society Act,Ukwimi,POULTRY,40000.00
2,2,SONGOVWA SAVINGS AND CREDIT COOPERATIVE SOCIET...,Community,4,6,6,10,0,0,coperative society Act,Ukwimi,PIGERY,40000.00
3,3,CHAKULETA MULTIPURPOSE COOPERATIVE SOCIETY LTD,Community,6,4,5,10,0,0,coperative society Act,Ukwimi,PIGERY,35000.00
4,4,NTHUDZA FARMERS GROUP,Community,6,4,9,10,0,0,coperative society Act,Ukwimi,PIGERY,35000.00

TABLE 8

,0,1,2,3,4,5,6,7,8
0,1,Mirrian Mwanza,Ukwimi,F,Financial Challenge,Environmental Health,36.0,Lusaka,Evelyn Hone College
1,2,Ephraim Lumamba,Ukwimi,M,Financial Challenge,Plumbing and pie fitting TtL1,24.0,Lusangazi,Ukwimi Trades Training Institute
2,3,John Banda,Ukwimii,M,Financial Challenge,Driving classes,1.0,Lusangazi,Ukwimi Trades Training Institute
3,4,John Tembo,Ukwimi,M,Financial Challenge,Electric Technology,24.0,Lusangazi,Ukwimi Trades Training Institute
4,5,John Banda,Ukwimi,M,Financial Challenge,Carpentry and Joinery,24.0,Lusangazi,Ukwimi Trades Training Institute

TABLE 9

,0,1,2,3,4,5,6,7,8,9
0,No.,Name of Pupil,Ward,Sex (M/F),Type of Vulnerability,Grade,Name of School,School Location(District),Termly Fees,Annual Fees
1,1,MARTHA MWALE,NYAKAWISE,FEMALE,Single ophan,10,Petauke Boarding Secondary School,PETAUKE,1000,3000
2,2,THERESA NYANOKA,NYAKAWISE,FEMALE,Single ophan,10,Petauke Boarding Secondary School,PETAUKE,1000,3000
3,3,FELIX MUMBA,NYAKAWISE,MALE,Single ophan,10,Petauke Boarding Secondary School,PETAUKE,1000,3000
4,4,GODFREY PHIRI,NYAKAWISE,MALE,Single ophan,10,Nyamphande Boarding Secondary School,LUSANGAZI,1000,3000